all:
	gcc main.c vec.c sdl_c.c font.c buffer.c -Wall -Wextra -Wshadow -pedantic -lfreetype -lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf -lfreetype -o main

prod:
	gcc main.c vec.c sdl_c.c font.c buffer.c -Wall -Wextra -Wshadow -pedantic -lfreetype -lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf -lfreetype -o main -mwindows
